package com.huysg136.cirquo_server.user.enums;

public enum PermissionName {

    USER_READ,
    USER_UPDATE,
    USER_BLOCK,
    USER_UNBLOCK,
    USER_ASSIGN_ROLE,
    USER_MANAGE_PERMISSION,

    ROLE_READ,
    ROLE_MANAGE,

    PERMISSION_READ,
    PERMISSION_MANAGE,

    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    BRAND_CREATE,
    BRAND_UPDATE,
    BRAND_DELETE,

    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_PUBLISH,
    PRODUCT_UNPUBLISH,

    PRODUCT_VARIANT_CREATE,
    PRODUCT_VARIANT_UPDATE,
    PRODUCT_VARIANT_DELETE,

    PRODUCT_IMAGE_CREATE,
    PRODUCT_IMAGE_DELETE,

    INVENTORY_READ,
    INVENTORY_ADJUST,

    STOCK_MOVEMENT_READ,
    STOCK_MOVEMENT_CREATE,

    COUPON_READ,
    COUPON_CREATE,
    COUPON_UPDATE,
    COUPON_DEACTIVATE,

    ORDER_READ,
    ORDER_READ_ALL,
    ORDER_UPDATE_STATUS,
    ORDER_CANCEL,

    PAYMENT_READ,
    PAYMENT_VERIFY,

    REFUND_READ,
    REFUND_APPROVE,
    REFUND_REJECT,

    SHIPMENT_READ,
    SHIPMENT_CREATE,
    SHIPMENT_UPDATE_STATUS,

    REVIEW_MODERATE,

    LOYALTY_READ,
    LOYALTY_ADJUST,

    USER_EVENT_READ,
    PRODUCT_RELATION_MANAGE,
    RECOMMENDATION_REFRESH
}
